<?xml version="1.0" encoding="UTF-8" ?>
<config>	
	<paths>
		<root>${born-properties.paths.root}</root>
	</paths>
	<hosts>
		<root>${born-build.hosts.public}</root>
	</hosts>
	<system>
		<username>${build.username}</username>
	</system>
    <libs>
        <Pifa>
            <modules>
                <Db>
                    <host>${born-properties.db.host}</host>
                    <dbname>${born-properties.db.name}</dbname>
                    <username>${born-properties.db.username}</username>
                    <password>${born-properties.db.password}</password>
                </Db>
            </modules>
        </Pifa>
    </libs>
</config>